language: python

python:
    - "2.7"
    - "3.3"

install:
    - pip install pep8 pylint nose
    - python setup.py develop

script:
    - pep8 --ignore=E501 gocdapi/*.py
    - pylint --rcfile=pylintrc gocdapi/*.py
