language: python

python:
    - "2.7"

install:
    - pip install pep8 pylint nose coverage nose-testconfig
    - python setup.py develop

script:
    - find gocdapi -name "*.py" | xargs pep8 --config=.pep8rc
    - find gocdapi -name "*.py" | xargs pylint --rcfile=.pylintrc
    - nosetests -s --nologcapture
